model:
  encoder: han
  decoder: han
  hidden_dim: 64
  num_layers: 2
  num_heads: 4
  num_out_heads: 1
  activation: prelu
  norm: layernorm
  residual: true

dropout:
  feat_drop: 0.2
  attn_drop: 0.2
  negative_slope: 0.2

masking:
  feat_mask_rate: "0.3"
  replace_rate: 0.1
  leave_unchanged: 0.1
  loss_fn: sce
  alpha_l: 3.0

edge_recon:
  use_mp_edge_recon: false
  mp_edge_mask_rate: "0.3"
  mp_edge_recon_loss_weight: 1.0
  mp_edge_alpha_l: 3.0

mp2vec:
  use_mp2vec_feat_pred: false
  mps_embedding_dim: 64
  mp2vec_feat_pred_loss_weight: 1.0
  mp2vec_feat_alpha_l: 3.0
  mp2vec_feat_drop: 0.2

training:
  mae_epochs: 200
  lr: 1.0e-3
  l2_coef: 1.0e-4
  patience: 20
  scheduler: false
  scheduler_gamma: 0.99

data:
  sample_ratio: 1.0
  use_cache: true
